version: '3.3'

services:
  server:
    image: word-games-server:prod
    build:
      context: ./packages/server
      target: prod
    ports:
      - ${SERVER_PORT:-5500}:3000
  client:
    image: word-games-client:prod
    build:
      context: ./packages/client
      target: prod
      args:
        - SERVER_URL=${SERVER_URL:-http://localhost:${SERVER_PORT:-5500}}
    ports:
      - ${CLIENT_PORT:-3000}:80