[package]
name = "letter-boxed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_enum = "0.2.0"
colored = "2.0.0"
itertools = "0.10.5"
queue = "0.3.1"
substring = "1.4.5"
threadpool = "1.8.1"
